# Generated by Django 5.2.17 on 2026-09-16 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('TRAFFIC', 'Multas de trânsito'), ('CONTRACTS', 'Contratos civis'), ('COLLECTION', 'Cobranças e dívidas'), ('LIABILITY', 'Responsabilidade civil'), ('CONSUMER', 'Relações de consumo'), ('PROPERTY', 'Imobiliário, posse e propriedade'), ('CIVIL_OTHER', 'Demais matérias civis')], max_length=20)),
                ('scope_acknowledged', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Enviado para distribuição'), ('EM_TRIAGEM', 'Em triagem'), ('AGUARDANDO_CLIENTE', 'Aguardando complemento'), ('ACEITO', 'Aceito na triagem'), ('RECUSADO', 'Recusado')], default='RASCUNHO', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submission_key', models.CharField(blank=True, max_length=64)),
                ('submission_version', models.PositiveIntegerField(null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=24)),
                ('version', models.PositiveIntegerField()),
                ('public', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='InformationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='information_requests', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='LocalCaseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['owner', '-created_at'], name='cases_case_owner_i_739a18_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['lawyer', 'state'], name='cases_case_lawyer__59b51b_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='case_positive_version'),
        ),
        migrations.AddConstraint(
            model_name='caseevent',
            constraint=models.UniqueConstraint(fields=('case', 'version'), name='case_event_version_unique'),
        ),
    ]
